name: CI

on: ["push"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
      - name: Set up credentials and build JAR file
        env:
          SECRETS_KEY: ${{ secrets.SECRETS_KEY }}
        run: |
          mkdir -p ~/.sbt/1.0
          ./secrets/decrypt.sh secrets/credentials.gpg ~/.sbt/.credentials
          sbt package
      - name: Deploy JAR to Artifcatory
        if: github.ref == 'refs/heads/master'
        run: |
          sbt publish
